language: python

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/h5py
    - $HOME/local

addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#      - kubuntu-backports
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - libhdf5-openmpi-dev
      - python-numpy
      - python-scipy
      

before_install:
  - pip install pyzmq
  - pip install codecov
  - pip install mpi4py
  - cd $HOME
  - if [ ! -d "$HOME/h5py/.git" ]; then git clone  https://github.com/h5py/h5py.git; else echo 'Using h5py from cached directory'; fi
  - mkdir -p h5py && cd h5py 
  - git pull
  - export CC=mpicc
  - python setup.py configure --mpi
  - python setup.py build
  - python setup.py install
  - export CC=''
  - pip install h5writer
  
install:
  - pip install pytest-cov

after_success:
  - codecov

script:
  - cd ${HOME}/build/FXIhub/hummingbird
  - coverage run --source hummingbird -m py.test  -v --color=yes --showlocals --durations=10